.PHONY: clean All

All:
	@echo "----------Building project:[ POTWAnswerProgram - Debug ]----------"
	@cd "POTWAnswerProgram" && "$(MAKE)" -f  "POTWAnswerProgram.mk"
clean:
	@echo "----------Cleaning project:[ POTWAnswerProgram - Debug ]----------"
	@cd "POTWAnswerProgram" && "$(MAKE)" -f  "POTWAnswerProgram.mk" clean
